package org.openjdk.kextract.impl

import org.openjdk.kextract.JavaSourceFile
import java.util.function.Function

internal class SourceFileBuilder private constructor(
    private val packageName: String,
    private val className: String
) {
    companion object {
        private val SHOW_GENERATING_CLASS = java.lang.Boolean.getBoolean("kextract.showGeneratingClass")

        fun newSourceFile(packageName: String, className: String): SourceFileBuilder {
            val sfb = SourceFileBuilder(packageName, className)
            sfb.emitPackagePrefix()
            sfb.emitImportSection()
            return sfb
        }
    }

    private val sb = StringBuilder()
    private var align = 0

    fun className(): String = className

    fun emitPackagePrefix() {
        assert(packageName.indexOf('/') == -1) { "package name invalid: $packageName" }
        appendLines("// Generated by kextract${if (SHOW_GENERATING_CLASS) " (via ${javaClass.name})" else ""}\n\n")
        if (packageName.isNotEmpty()) {
            appendLines("package $packageName;\n\n")
        }
    }

    fun emitImportSection() {
        appendLines("""
            import java.lang.invoke.*;
            import java.lang.foreign.*;
            import java.nio.ByteOrder;
            import java.util.*;
            import java.util.function.*;
            import java.util.stream.*;

            import static java.lang.foreign.ValueLayout.*;
            import static java.lang.foreign.MemoryLayout.PathElement.*;
            """.trimIndent() + "\n")
    }

    fun incrAlign() { align++ }
    fun decrAlign() { align-- }

    fun toFile(suffix: String, finisher: Function<String, String>): JavaSourceFile =
        JavaSourceFile("$className$suffix", packageName, finisher.apply(sb.toString()))

    fun toFile(finisher: Function<String, String>): JavaSourceFile =
        toFile("", finisher)

    fun toFile(): JavaSourceFile = toFile { s -> s }

    fun appendLines(s: String) {
        val indent = "    ".repeat(align)
        s.lines().forEach { l ->
            sb.append(if (l.isEmpty()) "\n" else "$indent$l\n")
        }
    }

    fun appendIndentedLines(s: String) {
        incrAlign()
        appendLines(s)
        decrAlign()
    }
}
