// Uses the Kotlin bindings generated by kextract from hello.h.
// Run ./run.sh to generate, compile and execute.
import org.example.hello.hello
import org.example.hello.add

fun main() {
    hello()
    val result = add(40, 2)
    println("40 + 2 = $result")
}
