#!/bin/sh
ROOT=`dirname $0`/..
LIBS="$ROOT/lib/org.graphiks.kextract.jar"
for jar in "$ROOT/lib/"*.jar; do
    case "$jar" in
        *org.graphiks.kextract*) ;;
        *) LIBS="$LIBS:$jar" ;;
    esac
done
$ROOT/runtime/bin/java $JEXTRACT_JAVA_OPTIONS \
  --enable-native-access=ALL-UNNAMED \
  -Djava.library.path="$ROOT/lib" \
  -cp "$LIBS" \
  org.graphiks.kextract.pipeline.KextractTool "$@"
