#!/bin/sh
ROOT=`dirname $0`/..
LIBS="$ROOT/lib/org.openjdk.kextract.jar"
for jar in "$ROOT/lib/kotlin-stdlib-"*.jar; do
    LIBS="$LIBS:$jar"
done
$ROOT/runtime/bin/java $JEXTRACT_JAVA_OPTIONS \
  --enable-native-access=ALL-UNNAMED \
  -Djava.library.path="$ROOT/lib" \
  -cp "$LIBS" \
  org.openjdk.kextract.newimpl.KextractTool "$@"
