// Uses the Kotlin bindings generated by kextract from Greeter.h (ObjC mode).
// Run ./run.sh to generate, compile and execute.
//
// NOTE: requires the ObjC support to be implemented in kextract
// (see the ObjC implementation plan).
import org.example.greeter.Greeter_h
import org.example.greeter.ObjCRuntime
import java.lang.foreign.Arena

fun main() {
    Arena.ofConfined().use { arena ->
        // Greeter.create() — class method (+)
        val greeterPtr = Greeter_h.Greeter.create()
        val greeter = Greeter_h.Greeter(greeterPtr)

        // greetWithName: — instance method (-)
        val namePtr = ObjCRuntime.newNSString(arena, "World")
        val resultPtr = greeter.greetWithName(namePtr)

        println(ObjCRuntime.toJavaString(resultPtr))
    }
}
